# This file was generated by https://github.com/lionello/dub2nix v0.2.9
[ {
  fetch = {
    type = "git";
    url = "https://github.com/vibe-d/vibe.d.git";
    rev = "v0.9.5";
    sha256 = "1cf8psyfxh7053wwcjm3jm9avyph6dkx7c4fahi0gr1lrflpvpcb";
    fetchSubmodules = false;
    date = "2022-07-18T17:27:21+02:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/dx5wdsw6rrwxrhg1vqx1a1p7jq89rz5g-vibe.d";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/wilzbach/stdx-allocator.git";
    rev = "v2.77.5";
    sha256 = "03av8zp5p6vf6fg005xbmwnjfw96jyrr4dcj4m56c4a3vx7v72pk";
    fetchSubmodules = false;
    date = "2018-12-23T13:54:22+01:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/b3h25asfh205wzwjfzjf2k2kkccpp96k-stdx-allocator";
  };
} ]