# This file was generated by https://github.com/lionello/dub2nix v0.2.4
[ {
  fetch = {
    type = "git";
    url = "https://github.com/vibe-d/vibe.d.git";
    rev = "v0.9.4";
    sha256 = "0kjnrlz30gvb08v79d7x5laapk13fxyj1cfr31wx0px3xrnjpzfq";
    fetchSubmodules = false;
    date = "2021-09-30T14:24:53+02:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/3x9z474xs6d65w1my3s7kbr45z938rnc-vibe.d";
  };
} {
  fetch = {
    type = "git";
    url = "https://github.com/wilzbach/stdx-allocator.git";
    rev = "v2.77.5";
    sha256 = "03av8zp5p6vf6fg005xbmwnjfw96jyrr4dcj4m56c4a3vx7v72pk";
    fetchSubmodules = false;
    date = "2018-12-23T13:54:22+01:00";
    deepClone = false;
    leaveDotGit = false;
    path = "/nix/store/b3h25asfh205wzwjfzjf2k2kkccpp96k-stdx-allocator";
  };
} ]